// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentOrders.Infrastructure.Persistence;

#nullable disable

namespace PaymentOrders.Infrastructure.MySqlMigrations.Persistence.Migrations
{
    [DbContext(typeof(PaymentOrdersDbContext))]
    partial class PaymentOrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PaymentOrders.Domain.Orders.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Commission")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceAccount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SwiftCode")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("TargetAccount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("payment_orders", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PaymentOrders.Domain.Orders.PaymentOrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PaymentOrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentOrderId", "OccurredAt");

                    b.ToTable("payment_order_events", (string)null);
                });

            modelBuilder.Entity("PaymentOrders.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PaymentOrderId")
                        .HasColumnType("char(36)");

                    b.HasKey("Key");

                    b.HasIndex("PaymentOrderId");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("PaymentOrders.Domain.Orders.InternationalPaymentOrder", b =>
                {
                    b.HasBaseType("PaymentOrders.Domain.Orders.PaymentOrder");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("PaymentOrders.Domain.Orders.NationalPaymentOrder", b =>
                {
                    b.HasBaseType("PaymentOrders.Domain.Orders.PaymentOrder");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("PaymentOrders.Domain.Orders.ScheduledPaymentOrder", b =>
                {
                    b.HasBaseType("PaymentOrders.Domain.Orders.PaymentOrder");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("PaymentOrders.Domain.Orders.PaymentOrderEvent", b =>
                {
                    b.HasOne("PaymentOrders.Domain.Orders.PaymentOrder", null)
                        .WithMany("AuditEvents")
                        .HasForeignKey("PaymentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaymentOrders.Domain.Orders.PaymentOrder", b =>
                {
                    b.Navigation("AuditEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
